[server]
heartbeat_interval_ms = 1000
connection_pool_size = 16

[meta]
min_sst_retention_time_sec = 21600
full_gc_interval_sec = 3600
full_gc_object_limit = 100000
periodic_compaction_interval_sec = 300
vacuum_interval_sec = 30

[batch]
statement_timeout_in_sec = 3600

[streaming]
in_flight_barrier_nums = 10000
async_stack_trace = "ReleaseVerbose"

[storage]
shared_buffer_capacity_mb = 256
compactor_memory_limit_mb = 1024
compactor_memory_available_proportion = 0.8
max_concurrent_compaction_task_number = 4
compactor_max_task_multiplier = 3.0
min_sst_size_mb = 32

[storage.object_store]
retry = { req_backoff_interval_ms = 1000, req_backoff_max_delay_ms = 10000, req_backoff_factor = 2 }

[storage.cache]
block_cache_capacity_mb = 256
meta_cache_capacity_mb = 256
